org: buddyandme
app: buddyandme
service: buddyandme-service

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  stage: dev
  apiGateway:
    binaryMediaTypes:
      - 'application/octet-stream'
  environment:
    OPENAI_API_KEY: ${param:OPENAI_API_KEY}
    DYNAMODB_TABLE: UserMessagesTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}

functions:
  app:
    handler: lambda_function.lambda_handler
    events:
      - http:
          path: /
          method: post
          integration: lambda

resources:
  Resources:
    UserMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserMessagesTable
        AttributeDefinitions:
          - AttributeName: UserID
            AttributeType: S
        KeySchema:
          - AttributeName: UserID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**

plugins:
  - serverless-python-requirements
