org: buddyandme
app: buddyandme
service: buddyandme-service

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  stage: dev
  apiGateway:
    binaryMediaTypes:
      - 'audio/mpeg'
  environment:
    OPENAI_API_KEY: ${param:OPENAI_API_KEY}
    DYNAMODB_TABLE: UserMessagesTable
    AZURE_REGION: ${param:AZURE_REGION}
    AZURE_API_KEY: ${param:AZURE_API_KEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}
    - Effect: Allow
      Action:
        - lambda:GetLayerVersion
      Resource:
        - arn:aws:lambda:ap-southeast-1:339713051410:layer:ffmpeg-python-layer:2

functions:
  app:
    handler: lambda_function.lambda_handler
    timeout: 30
    memorySize: 1024
    layers:
      - arn:aws:lambda:ap-southeast-1:339713051410:layer:ffmpeg-python-layer:2
    events:
      - http:
          path: /
          method: post
          integration: lambda-proxy

resources:
  Resources:
    UserMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserMessagesTable
        AttributeDefinitions:
          - AttributeName: UserID
            AttributeType: S
        KeySchema:
          - AttributeName: UserID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    layer: true
