org: buddyandme
app: buddyandme
service: buddyandme-service

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}  # Default to 'dev' if no stage is provided
  apiGateway:
    binaryMediaTypes:
      - 'audio/mpeg'
  environment:
    OPENAI_API_KEY: ${param:OPENAI_API_KEY}
    DYNAMODB_MESSAGES_TABLE: ${self:custom.dynamodbTable.${self:provider.stage}.messages}
    DYNAMODB_PROMPTS_TABLE: ${self:custom.dynamodbTable.${self:provider.stage}.prompts}
    AZURE_REGION: ${param:AZURE_REGION}
    AZURE_API_KEY: ${param:AZURE_API_KEY}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_MESSAGES_TABLE}
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_PROMPTS_TABLE}
    - Effect: Allow
      Action:
        - lambda:GetLayerVersion
      Resource:
        - arn:aws:lambda:ap-southeast-1:339713051410:layer:ffmpeg-python-layer:2

functions:
  app:
    handler: lambda_function.lambda_handler
    timeout: 30
    memorySize: 1024
    layers:
      - arn:aws:lambda:ap-southeast-1:339713051410:layer:ffmpeg-python-layer:2
    events:
      - http:
          path: /
          method: post
          integration: lambda-proxy

resources:
  Resources:
    UserMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodbTable.${self:provider.stage}.messages}
        AttributeDefinitions:
          - AttributeName: UserID
            AttributeType: S
        KeySchema:
          - AttributeName: UserID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    UserPromptsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodbTable.${self:provider.stage}.prompts}
        AttributeDefinitions:
          - AttributeName: UserID
            AttributeType: S
        KeySchema:
          - AttributeName: UserID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    layer: true

  dynamodbTable:
    dev:
      messages: UserMessagesTable_Dev
      prompts: UserPromptsTable_Dev
    prod:
      messages: UserMessagesTable_Prod
      prompts: UserPromptsTable_Prod
